name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install required packages
      run: sudo apt-get install -f yamllint

    - name: Run docker check
      run: |
        make docker-lint
        popd
    - name: Run yaml check
      run: |
        make yaml-lint
        popd
